spring:
  profiles:
    include: jwt, oauth, prd
  cloud:
    config:
      enabled: false

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
