server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  data:
    User_Server: "http://192.168.30.143:8080"
    Order_Server: "http://localhost:8080"
    Notification_Server: "http://192.168.30.215:8080"
    Store_Server: "http://192.168.30.215:8080"
    Kafka_Server: "k9e205.p.ssafy.io:9092"
