server:
  port: 9000
spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:slbin-park/config-test.git
          ignore-local-ssh-settings: true
          private-key: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIJKAIBAAKCAgEA3oxIUSY2//09cmO8rqDCHVHq2lBhh2FJyv/LseRz49FVh6MF
            eLvOAnjayrZo83Dh7z0eQ30NJvL4aGVL7nHG8L+DjFysrd9Ma0t2jkhIXcNnYOHU
            3W3i9fQ5J5cQWeaeKKaDRBXGogKn0okyxizBQT3OpzXJzGXz988EEJTj/GAUjumE
            dP9CAXqJEktfn89gU495XeHPQIYhCKX4BHfvdhA01G34YTPHmERONJd9N3sNU5Ao
            QkIt4BovykjXnnqCEolih2XvJqbVnmHPFTi0zcpbFNdEeWqiVWaKmlCKzGiPehKO
            VY4/H5Rw4r3iRCVgot4IaWt+CLcLjMEpq4Q0SqAS9BPwIWlQ1R8uOowUA6vzN62D
            Tx4xzSbNIAXupRr4ha5E71UKK5g26xcaTcTLx4Li3ILT+ZqcHQhTVXi2vgE4ERGA
            XJnKQRRr7o4PrrFu3IzghmgUvDQ6U96PhbHjOe4FYQ5rijH21/UHPPpJe4FUUBJ2
            vXsyGrXEEB7037ZX0SRuEj5Ru9SitDEA9Of7dU3ID5qYQnaOcnWHsImzU59nfCD2
            x2TWvHmfVoWRC8ic3gg4k7asT4RJTF3CsvL3uPdhgvcBk1O46ox68d5TOP1w+5Ng
            CFJjh28kUt03RdAerpTzsu1EDNfUYfnbI5n6Tj9nmYLZCAhZHSLjg6q6OcUCAwEA
            AQKCAgEA1KtyIDpIrPCv27R8BtURKzuxFtdhnCHYhulTGriaFsdg2LFs9SdjgvFD
            BBy0xo7FGf5qAUxrWSEvSXQjz8Viu4YIjAWz7qRJPu9qaCWjIhctn2OwK7pq/WdZ
            hv/RXFgKJAabwmCc5Q1smsEJiGAUfeg2p4u7QFzde56U39Oo2vBmNPvq3HNh/E/A
            1X657toZz0B4VsMHbz2+K6mPDZYfe8+Y7Lf6d8knn9cGdTOfMXmiDozgLBFaDaJ4
            sPJTOtsPme83/PPoSiN8WFJXtovuHAqYZ54fjXfdkYbgRP9a5GO3WIyLAC9jGyab
            idKzezPM2Vcc6sESO/nQS737uDAqVq2aRnqXtKuT4Wwhqa01FSVC09G4rUKdTWYU
            3zbEOVJ5GSlaqEH2+/IUvpHJv1Dip/+Axc3SuPBDwidSmunOe8YnYdpSP9IhzNRs
            4i4DNJqIG9hD4Mbvpc7e4SM6d0txPGcn2wTtCnwJLTmISENwkIE6t7uSM2fO8rtb
            zRvEe2CkLdeWbmF1/J5ym3FgbDieTQXY1rX2ej3looFzKjQ/HyssBdHwA+KuQf9A
            7amVHz8D1T5dOQzWP7IShTPNjiwC09J+ylivJ5NPNPVcc2X5Ocf31x98TkpnxEFo
            QeupiNU5ahjskYTFimeSEl8GFFrNJeQn1Av5HvEEzzjaGalu4gECggEBAPaUNPEm
            VnWRr7N474ueK2KxFcb1PNhGbrmcNiRGKTcH3JM9wp5O3N95mfWFmtWYEPyVNdSj
            D7jPBlgVTQevKK/tMKL+C6CKpAkhRdZSzLOVa7T5vLkMWOBZqVrDEIqJP+rzX7LH
            HKKIbHV/2DoX2IG7Ex5CCLAgeAMiVN4o5Mix3XGrhIZvbBT6e+mpXq8seOHytwiZ
            jA+kkCaO5rWC4QW18N5cHkg8ssGV79hGouCgZJGeUtTIPMyNXEy1o6thtpwf4hEE
            axcFH40kovdSsuVkvJ7Pri0tqvdE8z2Fe+w8WZFgmAk2ek/D+UKangepg0pQji5m
            8epHJZ7kW+rhCCECggEBAOcNB0mDgUNndEuqN16UNunSC5R0/m0u0I4+Fjm9m8NL
            aExoRhZWEtupUUz5TJXz7Q+k/X21qyIF6cLQOunzyu2jubC6bCm4nItkEs3reJbO
            NvHVpfJDrAMBUWmKlmLyab/zTna8H01kmr11XjIBpe8nNKelFmXIwDvVvZOfO3m9
            w7XhvgjVe/Vrtxfku/iSywaVWQhzGDnBBb5o/K5uNLh8H2/WqNbPF7Vw/oONgkgZ
            KybVrHGp8eJy74itLBU0uW2CW1RAKRf3um6YvLw1z6ZntuOcWJ0ZrasUjFORl6qd
            jFnUPEoZtTTWiWEyi2viwEJB5euzEVnIhPUFu/f+bSUCggEAVVEqkFYHjF6AQMUT
            fWeY82j6dADesKaOIULfqOVt1VCvDXNNJ6F54wkcMEuuK0GWfw7RtWVGR1e6hje4
            k3QTy+tx7LOiKkZOQ6pzk5jKo0iMH+5ZUl3nUpkzc+gSjRy4NP9ImX8zdTlm7bDy
            jAc8LocgMlP+1ZImdE8otkXIA3knefEyxaE/8HJK9apYzJvCp8tncV5PjAoQpobD
            ZQKIAYXWddnB0JTP9ROADYFDUh2tLoVte5pdDxnKWfBvVRlWKecOPX0d4LUxGZEX
            oiPHKoAUk46gYZlvkmcVErBhFHg9NYQKlwV2hKr2UAlXrKcGemwtBfkwszMy3St+
            cmKygQKCAQAhICkPTR9XPpnZz0mo8a79zvOCEVP462FTQ2uEU77lPQZzDfAee7Cw
            dZIGayejyBkQySLexxEGC7r8B0arDBzn/TU+NTwUrzcidPKNO1lKpb4S5gKovTMI
            K0Q00X3GKeMndgal10rVmbrlttIOcVYM954A+xY++Y02BurrI0UvqxlIFllcgt8G
            zK6vakfY15LsGrVtFLNAdIASUJMJnxtH5+PJ8Qi7420Owmh7C+rF03XwV2ol0auw
            P7I/8jQDxk9fd/UIGzrJCOddu+AzS7O9s9jwwRWjUG8pvARyZslL2NKqflc2eIEW
            VjvUB58dlKDj3vbL2ByAttL5Hh1Y7M1RAoIBAHiph8gEJ2CRT28u5QhEVvnRn2k3
            tO4TbB4nBQh0v6GaQqRW8ux6aJQ9ZC5+16tnGzVaSv4BkfrxnKCAG06dm3skhKDE
            gS5ZPBm0KAqdh4mmYKiF4Vie1m8fAcXroUBTcXZhuZCdh2jw8cvUQvmZLLAauun8
            hg85ADKKt9QKXj4BxJq5cBof9DnxMuF520CuQ98k1XggwaOG1DsdaiBgMEqfLiCo
            u8nPJ2B1yxK8k6cUdfs+F5d+0zfELEGxN2/uDujqkR8EliB5U1ad9AxxGPC0GVm6
            cXeiocuOQY1Dr7Pr+oB3kPL3+/xwO0rct8ykkNOQQqehO7VwCs2kSeewKQI=
            -----END RSA PRIVATE KEY-----