server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

feign:
  storeserver:
    url: k9e205.p.ssafy.io:8090
  userserver:
    url: k9e205.p.ssafy.io:8100
  payserver:
    url: k9e205.p.ssafy.io:8110
  notiserver:
    url: k9e205.p.ssafy.io:8120
  orderserver:
    url: localhost:8080 #k9e205.p.ssafy.io:8130
  ownerserver:
    url: k9e205.p.ssafy.io:8140