export const nearvendors = [
  {
    storeId: 10,
    ownerId: 1,
    name: '가게이름',
    ownerName: '사장이름',
    phone: '휴대폰번호',
    category: 'HOTTEOK',
    businessCategory: '푸드트럭',
    openTime: '00:00:00',
    closeTime: '12:00:00',
    activeArea: '주소',
    lati: 35.0870048,
    longi: 128.8536064,
    information: '안내변경',
    introduction: '설명 변경',
    state: 'OPEN',
  },
  {
    storeId: 2,
    ownerId: 2,
    name: '녹산 붕어빵',
    ownerName: '사장이름',
    phone: '휴대폰번호',
    category: 'FISHBREAD',
    businessCategory: '포장마차',
    openTime: '00:00:00',
    closeTime: '12:00:00',
    activeArea: '주소',
    lati: 35.0870048,
    longi: 128.8566064,
    information: '안내변경',
    introduction: '설명 변경',
    state: 'OPEN',
  },
];
