export const user = {
  points: 20000,
  email: 'test@test.com',
  nickname: '테스터',
  phone: '010-0000-1234',
  imageUrl: null,
  grade: 'LIGHT',
  role: 'USER',
  socialType: null,
  region1: '부산시',
  region2: '강서구',
  region3: '신호동',
  region4: '',
  paymentPassword: '123456',
};
