export const vendordata = [
  {
    id: 10,
    name: '녹산 호떡 트럭',
    lat: 35.0870048,
    lng: 128.8536064,
    category: 1,
    review: 4.8,
    phone: '010-1111-1111',
    introduction: '녹산 호떡 트럭 소개입니다.',
    starttime: '08:00',
    endtime: '17:00',
    loc: '갑을 녹산 병원 앞',
    notice: '녹산 호떡 트럭을 찾아주셔서 감사합니다.더욱 맛있는 호떡을 만들어 드리겠습니다.',
    menulist: [
      {
        id: 1,
        name: '호호떡',
        menuimg: '/images/orderfunding/menuimg.png',
        options: [
          {
            id: 1,
            name: '꿀 빼주세요',
            price: 500,
          },
          {
            id: 2,
            name: '꿀 더주세요',
            price: 500,
          },
        ],
        price: 8000,
      },
    ],
    reviewlist: [],
  },
  {
    id: 2,
    name: '녹산 붕어빵',
    lat: 35.0870048,
    lng: 128.8566064,
    category: 2,
    review: 4.3,
    phone: '010-1234-1111',
    introduction: '세계 최강 맛있는 붕어빵집 세계 최강 붕어빵 입니다. 색다른 붕어빵들을 먹어보세요.',
    starttime: '08:00',
    endtime: '17:00',
    loc: '녹산동 다이소 앞',
    notice: '세계 최강 붕어빵을 찾아주셔서 감사합니다.더욱 맛있는 붕어빵을 만들어 드리겠습니다.',
    menulist: [
      {
        id: 1,
        name: '세계 최강 팥 붕어빵',
        menuimg: '/images/orderfunding/menuimg.png',
        options: [
          {
            id: 1,
            name: '초코크림 빼주세요',
            price: 500,
          },
          {
            id: 2,
            name: '초코크림 더주세요',
            price: 500,
          },
        ],
        price: 8000,
      },
      {
        id: 2,
        name: '세계 최강 슈크림 붕어빵',
        menuimg: '/images/orderfunding/menuimg.png',
        options: [
          {
            id: 1,
            name: '슈크림크림 빼주세요',
            price: 500,
          },
          {
            id: 2,
            name: '슈크림크림 더주세요',
            price: 500,
          },
        ],
        price: 9000,
      },
    ],
    reviewlist: [
      {
        reviewid: 1,
        userid: 1,
        username: '붕어빵조아',
        stars: 3.0,
        content: '세계에서 가장 맛있는 붕어빵이네요 잘먹었습니다!',
      },
      {
        reviewid: 2,
        userid: 24,
        username: '붕어빵시러',
        stars: 1.0,
        content: '아무리 맛있어도 붕어빵은 맛이 없어...',
      },
      {
        reviewid: 3,
        userid: 22,
        username: '붕어빵 킬러3',
        stars: 4.0,
        content: '세계에서 가장 맛있는 붕어빵이네요 잘먹었습니다!',
      },
      {
        reviewid: 4,
        userid: 22,
        username: '붕어빵 킬러4',
        stars: 5.0,
        content: '세계에서 가장 맛있는 붕어빵이네요 잘먹었습니다!',
      },
      {
        reviewid: 5,
        userid: 22,
        username: '붕어빵 킬러5',
        stars: 5.0,
        content: '세계에서 가장 맛있는 붕어빵이네요 잘먹었습니다!',
      },
    ],
  },
];
